// body><!-- Visible content of the webpage -->
//     <header> <!-- Header Section: Typically contains the main heading and navigation elements. -->
//         <h1>The Time Tracker</h1> <!-- Main heading of the page -->
//         <a class="nav-start" href="/index.html">/ © A Mind-Boggling Project /</a> <!-- Links to "index.html" page -->
//     </header>
//     <h2 id="switch"></h2> <!-- Empty header with ID for JavaScript manipulation -->
//     <form id="task-form"> <!-- Form element with an ID -->
//         <input type="text" name="task-input" id="task-input" placeholder="What are you working on?" /> <!-- Text input field with placeholder text -->
//         <input type="submit" id="task-submit" value="Add Task" /> <!-- Submit Button -->
//     </form>
//     <main> <!-- Main Section: Typically contains the main content of the webpage. -->
//         <section class="task-list"> <!-- Section: created to add tasks here. -->
//             <h2>Tasks</h2> <!-- Subheading for the task list. -->
//             <div id="tasks"> <!-- Container element. Will hold task elements dynamically generated by JavaScript. -->
//                 <!-- Commented out code below is a template for an individual task element -->
//                 <!-- Commented out code below was commented out in original code. -->
            
//                         <div class="task">
//                             <div class="content">
//                                 <input type="text" class="text" value="A new task" readonly />
//                             </div>
//                             <div class="counter">
//                                 <div class="time">
//                                     00:00:00
//                                 </div>
//                                 <div class="controls">
//                                     <button class="start">Start</button>
//                                     <button class="stop">Stop</button>
//                                     <button class="reset">Reset</button>
//                                 </div>
//                             </div>
//                             <div class="actions">
//                                 <button class="edit">Edit Task</button>
//                                 <button class="delete">Delete Task</button>
//                                 <button class="download">Download as CSV</button>
//                             </div>
//                         </div>
                   
//             </div>
//         </section>
//     </main>

//     <script src="main.js"></script> <!-- JavaScript code responsible for handling the interactions. -->
// </body>

// </html>


// Pseudo code

// - Create a switch statement which greets tells the visitor to have a happy day of the week
// - Create variables for form, input, and the div where the tasks will be listed
// - remove the default function of form submission
// - creat a function for capitalization of the first word in requested task
// - create a variable for what is entered into the form

// content

// - make a variable which creates a div where the contents (title) of one task will go
// - give the div the class of content
// - throw it inside the task list

// - make a variable which creates an input where the title of the task will go
// - give it the class of text
// - give it the value of what was entered into the original form
// - set it to not be editiable by default
// - throw it inside the content div

// counter

// - make a variable which creates a div where the timer will go
// - give the div the class of conunter
// - throw it inside the task list

// - make a variable which creates a div to show the time
// - give the div the class of time
// -throw it into the counter div

// - make a variable which creates a div where the button controls will go
// - give it the class of coutnrols
// - throw it inside the timers div

// buttons

// - make a variable which creates a new buttons
// - give the button the class of start
// - make this button say start


// - make a variable which creates a new buttons
// - give the button the class of stop
// - make this button say stop

// - make a variable which creates a new buttons
// - give the button the class of reseet
// - make this button say reset 

// - throw all three buttons into the control div

// actions

// - make a variable which creates a div where the button actions will go
// - give it the class of actions
// - throw it inside the task div

// action buttons
// - make a variable which creates a new buttons
// - give the button the class of edit
// - make this button say edit

// - make a variable which creates a new buttons
// - give the button the class of delete
// - make this button say delete task

// - throw these two buttons into the actions div

//  input value
 
// - set input value to an empty string

//  timer
// - create a second and interval variables and assign them starting values
// - add event listers with callback functions to the three counter buttons

// timer functions

// - write a function for the timer
// - include in the function for the time to appear in the time div

// - write a function for stopping
// - write a functiong for reseting

// edit 

// - add an event listener for the edit button that leads to a arrow function with conditionals

// delete

// - add an event listener to the delete button that leads to a arrow function 